# Generated by Django 5.1.2 on 2024-10-28 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='low_stock_alert',
            field=models.BooleanField(default=False),
        ),
    ]
